trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - k8s/backend.yml
      - k8s/frontend.yml

# agente donde se ejecutará el pipeline 
pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    persistCredentials: true

  # Backend - instalar dependencias
  - script: |
      cd backend
      npm ci
    displayName: Install backend dependencies

  # Backend - tests
  - script: |
      cd backend
      npm test
    displayName: Run backend tests

  # Backend - lint
  - script: |
      cd backend
      npm run lint
    displayName: Run backend lint

  # Backend - build y push
  - task: Docker@2
    displayName: Build and push backend
    inputs:
      command: buildAndPush
      containerRegistry: dockerhub-users-devsecops
      repository: oskrpov/users-backend
      Dockerfile: backend/dockerfile
      tags: |
        $(Build.BuildId)

  # Frontend - build y push
  - task: Docker@2
    displayName: Build and push frontend
    inputs:
      command: buildAndPush
      containerRegistry: dockerhub-users-devsecops
      repository: oskrpov/users-frontend
      Dockerfile: frontend/dockerfile
      tags: |
        $(Build.BuildId)

   # Actualizar tags de imagen en los manifiestos de Kubernetes     
  - script: |
      sed -i "s/:TAG/:$(Build.BuildId)/g" k8s/backend.yml
      sed -i "s/:TAG/:$(Build.BuildId)/g" k8s/frontend.yml

      echo "Backend:"
      grep "image:" k8s/backend.yml

      echo "Frontend:"
      grep "image:" k8s/frontend.yml
    displayName: Update Kubernetes image tags

  # commit y push de los manifiestos actualizados
  - script: |
      git config user.email "azure-pipeline@users-devsecops"
      git config user.name "Azure Pipeline"

      git add k8s/backend.yml k8s/frontend.yml
      git commit -m "Actualizando tag de imágenes a $(Build.BuildId)"
      git push origin HEAD:main
    displayName: Commit and push updated manifests