---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: users-backend-secret
  namespace: users-devsecops
spec:
  encryptedData:
    DB_PASSWORD: AgBh8YoRA7uig5JcOWBH+eWADv1HrgIuG3JTomLBItqUyEq0zv6CsVLdQ8knGuV0qnJeOE9TtfxFkBfBAZuZDIwZwLLqgOL+jHSozoQHEM0POuPLMfYvseMaiAsj9HykQ0eEbobA921Ye3pqhBH7LmXrFIV9tDDZGDrzjTIL4CTjs+xzeHQ/eP9ElKDdspjdGm3SNx3afL7Ri4DKZlcM9nhOzY1HeFOPWwkD7lvCSNInJGrF1whv5NTLCKsq4bGKUFhpKwKsDXHHc8sfIUV6Ks+X1jlqC1nqFrThkxt59A1PyW5rRMd68Qo5brA/MHikXqL9HghwN4kc71idDNskPgwM2XYjO/jJQxCryuRB2v+CtPV/JipSaXtFWc8zooDtfGCYGkd5eAxQilCsHXzbba+LRD5sMXWVJvGv3D+NXX9d9s5NdOP9PqqNSPxI6p6f1i92CoDXAlPWKIu4p8eoO69Hwnn4UL1X+9/StpQ8irdkAYyL0wKTlppm+ee1o2EWffasrcETjkVH9ZvKyX6vFBp6eSn4PjRZ2+94c6k/xosMW8shfegKKO6L0KS8gJ6VhNd1e9uuxWgdM83EgvZgxn51O0uEK3t0/AaTxPk2K5F1325VWmwDhIH0KY0yVvKCO2qqJ+9qUyQT9Bc3KTrrTvPohP4lCr3ezSZFh/FirLiPo6ERfE5fk66s9sg755Y+bmMNeroc/tc=
    DB_USER: AgCrFmczVqB7ISGQDly29cuhKmIn4GlxziS7b8tEEAhQN5yQTUiTWxbImPpld7TJ7y2oysaXfpB47Ls+HSKaoFn1kbXvVh6TA620xLPXAsHJmdUz1I2s9t6BIMhzUGIGsQ3AtZcr5S/931PhK0wvCBzgzHXERmd741STKVkpQv2VGLOLX0FkCz4cBNUMvRQ7BRlV77M9RBXyqavNC/lrHXOpnRCbBPAI9/g+ngBp57OlOutKRWSRFzHHK0VkF2Yq3yscaXOSq44AodstxNY2gESf3s3nlVkR+8Xnzm3OxuvTqnEw5e/2UTGa6Mvvra+KHIPZhVpne2G2hRe5KNoKYniPAj/m4PAOgPID+n/kcaw3IkPJDdKnx+klyGjxHS+XYSNx9cPDOXyZ/Togt7YPcRk14NO+rbIRptA/3QcQVPxSud9XE2Xc17POX6zrXL0irDsfOx5LhuNRKRKtpgdNaJhDDCkCiH4z5jXthSB7259GYWCIkVxgJtqjvdVooly76ubHT6BE4IuOa8G4UEf88fzn/D/+eUivhn9c12qmMXnjwMNCLXZGO2POjGudkWuXsG6p5L1jFNq51X1yyUFjaXiamjYOVqQHAcpilx7hS6pfAnjZ05dy24bs7bLc6QZpcwuT5s5O4Xvt+wLwUq0+wtITfCVfTBN2UI12ioNXQRlhwBk9mrmZRlL5qrCZKVk6m/iod+sHH1y4Qro=
  template:
    metadata:
      name: users-backend-secret
      namespace: users-devsecops
    type: Opaque
