---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: users-backend-secret
  namespace: users-devsecops
spec:
  encryptedData:
    DB_PASSWORD: AgAeX/FhMKmZXXiPrtud2tYVsdHPqcxomWg/hCXJPYbpH3wIEX/y2EFBWBjGIvsF5N7P1k89AjMaW/ShMy2Y4Bg4Mnvc5F6BdHh7w5W8/Po0jbVAowjHUl08ba7MeOhN5gWjE0Kh6CxO/llVsA161RcdQ7zVZNVMuUVl89JmcGnWzn0qO933/wKiJeGKzUqQl16gjn6PEXpCBDV6iS66AjW0WF6NoThCRgmjjHWzAzPhrtxTNfotCIfQirUF/Kww6eK1pxF0DHpTZMGOVs9JG2gSBdbhLgKO9PDauZuuLI6ML/YqQ4tfb9cmsVBqPaMSIPY4shboj6AVdundlP6WPLqfMe4xLMe2YBdU/v39Otyz4riVdrK+6sQL1py49DZCjRtjFNnQy5sjj11oZAkJK8BfaF3G4eFkXrYizuzcstx69AQjuGGT0e9wwOfFycpa3dXY6WyF7flplya9T/tGFpsQiKHPy2VOh31sm220S2QTxH7ktBkd9D+0gr5f1K+h40pZF0+YM9m8EevOU6QHE5J9DNbPNiPgZIfzWU0XmGu3PXBxALSqU+vMDQtcyRxOctHNLcvt1Pl527jIEJzyAJDXvXPTKHvWM10g1lbExMw5DC/fdtd2BRIy0wZOpiNL26A1WYUxCq3ihrrVA+7mA4DheWQpBjLlErVjFgB4HFxexNcF07frmi+/U7P7WJ/SCknkFiuWpEk=
    DB_USER: AgAtP/vh5qxbCLNla0AG3fbU6CWbhFdUBX7rWJMZMKKgBN0rB6QfGskduA1LHD2yLFYiGNMXBMYkr+izSktcpTkTKF/IuAapD9ZDkA3uphAC6VodPzy7WhsCqI3sLKhEasAFFLJR+5HnmN2CSv9f9wvbNo5ud0cPONvQnoSWoUgmOyHMQaoOeWh0SycAwzaGlQTqKi4XouXBqH2SExCUhVnJ20r9f/kQQuHfWyMJqhP0NRFHb8ioY+h1UAKXT8AV5mrq2cEaNOf/U6kFZSfJt5YzuDhP/2mY7POhDRnA1KST+uDVfslN0BH4BYYHdiUXptjT3S97mi43f0Gi+grsc0CEqScnN918q7C50jtCdnglTKlZDvyiWwlJewyos/eKmtds0O2vg2QRJFZqEPeYW+Dv4ms32YsvIMCnmJ/OmyEenp2fxM/bfsnDT61a6eStgH7RXUIOQwfTqZPxxAOcCR5ruh2bsil8uHncKAx+McK1p3Oos4vppFVaHn2lE3KvopA3k83STwD5NgXFdqiIPMNEww/U72fSwmZQ6Anz/lt3phH6BL//8JowgYVLHcPk6kVhKSMWOa96GSVae79NRmLeXVC2teewZQwlJ3REjIcxnqWGTMW/wXxQaYZBlt2QIPTtp6CSIun8znrHXb5TIWKSv5jwHWgaCvSsj0d445aDtE4OCpBKSNetpbZ2mz4g+KIWCW1ROwh5Cig=
  template:
    metadata:
      name: users-backend-secret
      namespace: users-devsecops
    type: Opaque
