---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: users-backend-secret
  namespace: users-devsecops
spec:
  encryptedData:
    DB_PASSWORD: AgC6pM42vb6pmd8a0ehe3nuvUiK3cJMT1xnObQpvqSoM+gH8XT2TUZHn0BTLYKt1ib5JZS4Yzu9bA8s7dLKhyYANDgzo05c4gEEZe9BCWgE3QbbTkXZIgTrmn8KFFdUV6u4FLH7mDDqAj6m9hMZV7Uohji1DDRHrFXZGpalCFfHru6p2iHdQl5Lywo0GOUz1V38lmynXgNxy2VRxGy+DulTMTGYAr6Qkwyb+y+uWqKvEqNrV5dwSfgJ+tbt0EY1InBSbYpdtXkSEdeZLNhjnPAvZV02ECsy+AP2g0Y137AfxeSBTWaAyxcrY5sMEnU6h/HZ77Z9vNSRN/bwdaehco8cFfhewtQjmXnLjkq6MxLNjI7dm2YaosZe+d1amFvNkhDuKcA//PBl8CSoq0w76tInTs6eRNG2kykP5j3NI1iveg1kbqUBDBn0lMkYosFXbSSnq/bYqKFq0Kd1q/XlfGbdwL3S6ygp7X28HS3nfRG4iyCKRCSjodXv390AcHRO4ULIvd7wFdoEq/bYmT6ToNcmnwMVXRV7edC3Uj077xW+Lsp0KNQiXpeef9MErarEDApNMWE3H/fz6oKEBh4YBfRx7lfJ1m6vpsqPLZtkjd83ks6Z1oNB4pDc7XG1VS2VKIiVHhhA/SoGmYRCY4GnlDkpcgbvTJBHnbWkydaB9hMrK/+1auBU0PCy29bM6Vk5hr0rxinqkyEM=
    DB_USER: AgCn0U6GBq1ciDFXwdTVWPU/NBpAgq/Lap1u9V9FseJDEKBUPfZc7ubq4xQVy+WGLTGAAezw2PTN/7aOMYemXWRRFs8HI3qCdWl8Y6+xXAzNeCKVzLDsq+b3DPzXe6AMQ2FPQVoC3p+l9KJSD1204Q2i7QJoLbgXj7C67foG4D5yOL4IixXQUo/C8ewM/DpFIle41O7iCJjPmvO1+hum+x9I5p/Zxf5FEP2uwmurdhCUaOFTAse7594wf8Lxg74/Z3dhOnHV1bHxa8v5+OzH1SYZeHEmyVAD4VWPUagvB+xTHDpIn8+z8VCTNllau+Qt7Cmv9fXQPtS90UNPnya+N4e3rzEk0hnEoof9quEdwZ1sfUxXNd0z9/QJkOmx69jk/z9VOW3Fde1RbK9qL8ZFnYAWY9OB8W/0Yz+aH87klxcK0+6uXlHPLf10HIuu7lVe3WbDx/dVaxYEu+7VXGFjPpK807ov36LKJawfpDpeAPQqlO5cMDI7XT5TQCMbqV8kNnHGTAO4jNbDJ0YZpptIWKa7/4xzq2OfgC65K0eDcdLncynlGLrxPBITsO6ke+tEGu3kbZO/2iiTPhgHz6uv2Y1TBHj5E1QuXU5q7F7b6JD7i54+cab4/FaNmCHjnbeNTCayPrzeFUao4fhqEAegJ31kUaLfqTstBwiNhe54rw/Upqh5CPxf/KUXwlUmdJX/KhKsXmvHDoybZCI=
  template:
    metadata:
      name: users-backend-secret
      namespace: users-devsecops
    type: Opaque
